# Build settings
# markdown: rdiscount
markdown: kramdown
highlighter: pygments


# Site settings
title: xCode
email: core_bin@163.com
description: "个人博客，欢迎随便看看"
baseurl: ""
url: http://blog.hjhelp.com
username: maxwellxu


exclude: ['develop']
keep_files: ['.git','.svn']

nav:
  - text: Home
    url: /index.html
    icon: icon-home
    class: home
  - text: Archvies
    url: /archives.html
    icon: icon-reorder
    class: none
  - text: Categories
    url: /categories.html
    icon: none
  - text: About
    url: /about.html
    icon: icon-envelope-alt
    class: none

page:
  - text: 文章归档
    url: /archives.html
    last: true
  - text: 文章分类
    url: /categories.html
    last: true
  - text: 关于我
    url: /about.html
    last: 

author: 
  name: Mx
